# Generated by Django 3.2.8 on 2021-11-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
